### ISSUE TITLE
__init__.py - score -0.85 pylint

### ISSUE THREAD

**Issue by cmj77** [PaloAltoNetworks/safe-networking-sp#45]
************* Module project.__init__
C: 15, 0: Trailing whitespace (trailing-whitespace)
C: 24, 0: Trailing whitespace (trailing-whitespace)
C: 31, 0: Trailing whitespace (trailing-whitespace)
C: 35, 0: Trailing whitespace (trailing-whitespace)
C: 37, 0: Trailing whitespace (trailing-whitespace)
C: 38, 0: Trailing whitespace (trailing-whitespace)
C: 44, 0: Trailing whitespace (trailing-whitespace)
C: 49, 0: Trailing whitespace (trailing-whitespace)
C: 55, 0: Trailing whitespace (trailing-whitespace)
C: 57, 0: Trailing whitespace (trailing-whitespace)
C: 63, 0: Trailing whitespace (trailing-whitespace)
C: 64, 0: Trailing whitespace (trailing-whitespace)
C: 68, 0: Trailing whitespace (trailing-whitespace)
C: 69, 0: Trailing whitespace (trailing-whitespace)
C: 73, 0: Trailing whitespace (trailing-whitespace)
C: 74, 0: Trailing whitespace (trailing-whitespace)
C:111, 0: Line too long (101/100) (line-too-long)
C:112, 0: Line too long (104/100) (line-too-long)
C:121, 0: Trailing whitespace (trailing-whitespace)
C:124, 0: Trailing whitespace (trailing-whitespace)
C:126, 0: Trailing whitespace (trailing-whitespace)
C:127, 0: Wrong continued indentation (add 2 spaces).
                            maxBytes=app.config['LOG_SIZE'], 
                            ^ | (bad-continuation)
C:127, 0: Trailing whitespace (trailing-whitespace)
C:128, 0: Wrong continued indentation (add 2 spaces).
                            backupCount=app.config['LOG_BACKUPS'])
                            ^ | (bad-continuation)
C:129, 0: Line too long (128/100) (line-too-long)
C:133, 0: Line too long (110/100) (line-too-long)
C:134, 0: Line too long (112/100) (line-too-long)
C:139, 0: Trailing newlines (trailing-newlines)
************* Module project
C:  1, 0: Missing module docstring (missing-docstring)
E:  5, 0: Unable to import 'flask' (import-error)
E:  6, 0: Unable to import 'flask_bootstrap' (import-error)
E:  7, 0: Unable to import 'flask_elasticsearch' (import-error)
C: 12, 0: Constant name "app" doesn't conform to UPPER_CASE naming style (invalid-name)
C:120, 0: Constant name "bs" doesn't conform to UPPER_CASE naming style (invalid-name)
C:122, 0: Constant name "es" doesn't conform to UPPER_CASE naming style (invalid-name)
C:126, 0: Constant name "handler" doesn't conform to UPPER_CASE naming style (invalid-name)
C:129, 0: Constant name "logFormat" doesn't conform to UPPER_CASE naming style (invalid-name)
C:137, 0: Import "from project.views import sfn_blueprint" should be placed at the top of the module (wrong-import-position)
C:  8, 0: standard import "from logging.handlers import RotatingFileHandler" should be placed before "from flask import Flask" (wrong-import-order)

------------------------------------
Your code has been rated at -0.85/10

**Comment by sdndude** [comment]
Some of these, like the upper case naming style, are preferences in a config file.  For PEP8, the standard is to be consistent, not adhere to any special style.  Please fix that in the config file.  
Also, the placement of the imports is a consistency thing as well, as the order is affected only on dependency classes.  That should be noted in the config too.
Will get the rest fixed in develop

**Comment by sdndude** [comment]
This is fixed in 79f1dab
