### ISSUE TITLE
views.py score -24/10 pylint

### ISSUE THREAD

**Issue by cmj77** [PaloAltoNetworks/safe-networking-sp#46]
************* Module project.views
C:  1, 0: Missing module docstring (missing-docstring)
E:  1, 0: Unable to import 'flask' (import-error)
E:  2, 0: Unable to import 'flask' (import-error)
C:  6, 0: Constant name "sfn_blueprint" doesn't conform to UPPER_CASE naming style (invalid-name)
C:  8, 0: Missing function docstring (missing-docstring)
W:  1, 0: Unused jsonify imported from flask (unused-import)
W:  1, 0: Unused request imported from flask (unused-import)
W:  1, 0: Unused current_app imported from flask (unused-import)
W:  2, 0: Unused flash imported from flask (unused-import)

-------------------------------------
Your code has been rated at -24.00/10

**Comment by sdndude** [comment]
This is fixed in 79f1dab21906b363f73aa182eb155d871b614f94
