### ISSUE TITLE
dns.py score 4.03/10 pylint

### ISSUE THREAD

**Issue by cmj77** [PaloAltoNetworks/safe-networking-sp#47]
************* Module dns
C:  2, 0: Line too long (118/100) (line-too-long)
C: 81, 0: Trailing whitespace (trailing-whitespace)
C: 87, 0: Trailing whitespace (trailing-whitespace)
C: 94, 0: Trailing whitespace (trailing-whitespace)
C:  1, 0: Missing module docstring (missing-docstring)
E:  2, 0: Unable to import 'elasticsearch_dsl' (import-error)
C:  6, 0: Missing class docstring (missing-docstring)
C: 13, 4: Missing class docstring (missing-docstring)
R: 13, 4: Too few public methods (0/2) (too-few-public-methods)
C: 17, 4: Missing method docstring (missing-docstring)
C: 21, 4: Missing method docstring (missing-docstring)
C: 31, 4: Missing method docstring (missing-docstring)
W: 31, 4: Useless super delegation in method 'save' (useless-super-delegation)
C: 35, 0: Missing class docstring (missing-docstring)
R: 35, 0: Too few public methods (0/2) (too-few-public-methods)
C: 45, 0: Missing class docstring (missing-docstring)
C: 58, 4: Missing class docstring (missing-docstring)
R: 58, 4: Too few public methods (0/2) (too-few-public-methods)
C: 62, 4: Missing method docstring (missing-docstring)
C: 66, 4: Missing method docstring (missing-docstring)
C: 82, 4: Missing method docstring (missing-docstring)
W: 82, 4: Useless super delegation in method 'save' (useless-super-delegation)
C: 87, 0: Missing class docstring (missing-docstring)
C: 96, 4: Missing class docstring (missing-docstring)
R: 96, 4: Too few public methods (0/2) (too-few-public-methods)
C:101, 4: Missing method docstring (missing-docstring)
C:105, 4: Missing method docstring (missing-docstring)
C:116, 4: Missing method docstring (missing-docstring)
W:116, 4: Useless super delegation in method 'save' (useless-super-delegation)
C:121, 0: Missing class docstring (missing-docstring)
C:128, 4: Missing class docstring (missing-docstring)
R:128, 4: Too few public methods (0/2) (too-few-public-methods)
C:132, 4: Missing method docstring (missing-docstring)
C:136, 4: Missing method docstring (missing-docstring)
C:146, 4: Missing method docstring (missing-docstring)
W:146, 4: Useless super delegation in method 'save' (useless-super-delegation)
W:  2, 0: Unused Search imported from elasticsearch_dsl (unused-import)
W:  2, 0: Unused connections imported from elasticsearch_dsl (unused-import)
W:  2, 0: Unused Nested imported from elasticsearch_dsl (unused-import)

-----------------------------------
Your code has been rated at 4.03/10

**Comment by sdndude** [comment]
This is fixed in 79f1dab21906b363f73aa182eb155d871b614f94
