### ISSUE TITLE
dnsutils.py score -3.35/10 pylint

### ISSUE THREAD

**Issue by cmj77** [PaloAltoNetworks/safe-networking-sp#48]
************* Module dnsutils
C: 16, 0: Trailing whitespace (trailing-whitespace)
C: 17, 0: Trailing whitespace (trailing-whitespace)
C: 28, 0: Trailing whitespace (trailing-whitespace)
C: 29, 0: Trailing whitespace (trailing-whitespace)
C: 30, 0: Wrong continued indentation (remove 7 spaces).
                                    minute_points=0,
                             |      ^ (bad-continuation)
C: 31, 0: Wrong continued indentation (remove 7 spaces).
                                    minute_points_remaining=0,
                             |      ^ (bad-continuation)
C: 32, 0: Wrong continued indentation (remove 7 spaces).
                                    daily_points=0,
                             |      ^ (bad-continuation)
C: 33, 0: Wrong continued indentation (remove 7 spaces).
                                    daily_points_remaining=0,
                             |      ^ (bad-continuation)
C: 34, 0: Wrong continued indentation (remove 7 spaces).
                                    minute_bucket_start=now,
                             |      ^ (bad-continuation)
C: 35, 0: Wrong continued indentation (remove 7 spaces).
                                    daily_bucket_start=now)
                             |      ^ (bad-continuation)
C: 36, 0: Trailing whitespace (trailing-whitespace)
C: 37, 0: Trailing whitespace (trailing-whitespace)
C: 39, 0: Exactly one space required around assignment
    afDoc.minute_points=afInfo['minute_points']
                       ^ (bad-whitespace)
C: 40, 0: Exactly one space required around assignment
    afDoc.minute_points_remaining=afInfo['minute_points_remaining']
                                 ^ (bad-whitespace)
C: 41, 0: Exactly one space required around assignment
    afDoc.daily_points=afInfo['daily_points']
                      ^ (bad-whitespace)
C: 42, 0: Exactly one space required around assignment
    afDoc.daily_points_remaining=afInfo['daily_points_remaining']
                                ^ (bad-whitespace)
C: 43, 0: Exactly one space required around assignment
    afDoc.minute_bucket_start=afInfo['minute_bucket_start']
                             ^ (bad-whitespace)
C: 44, 0: Exactly one space required around assignment
    afDoc.daily_bucket_start=afInfo['daily_bucket_start']
                            ^ (bad-whitespace)
C: 62, 0: Trailing whitespace (trailing-whitespace)
C: 65, 0: Exactly one space required after comma
    queryResponse = requests.post(url=searchURL,headers=headers,
                                               ^ (bad-whitespace)
C: 69, 0: Trailing whitespace (trailing-whitespace)
C: 75, 0: Trailing whitespace (trailing-whitespace)
C: 79, 0: Trailing whitespace (trailing-whitespace)
C: 83, 0: Trailing whitespace (trailing-whitespace)
C: 86, 0: Trailing whitespace (trailing-whitespace)
C: 89, 0: Trailing whitespace (trailing-whitespace)
C: 96, 0: Trailing whitespace (trailing-whitespace)
C:102, 0: Trailing whitespace (trailing-whitespace)
C:112, 0: Trailing whitespace (trailing-whitespace)
C:113, 0: Wrong continued indentation (remove 3 spaces).
                    datetime.timedelta(days=app.config['DOMAIN_TAG_INFO_MAX_AGE']))
                 |  ^ (bad-continuation)
C:132, 0: Trailing whitespace (trailing-whitespace)
C:140, 0: Trailing whitespace (trailing-whitespace)
C:141, 0: Trailing whitespace (trailing-whitespace)
C:143, 0: Trailing whitespace (trailing-whitespace)
C:149, 0: Exactly one space required after comma
            tagDoc = TagDetailsDoc(meta={'id': tagName},name=tagName)
                                                       ^ (bad-whitespace)
C:154, 0: Trailing whitespace (trailing-whitespace)
C:155, 0: Trailing whitespace (trailing-whitespace)
C:158, 0: Trailing whitespace (trailing-whitespace)
C:162, 0: Trailing whitespace (trailing-whitespace)
C:167, 0: Trailing whitespace (trailing-whitespace)
C:169, 0: Line too long (105/100) (line-too-long)
C:170, 0: Trailing whitespace (trailing-whitespace)
C:171, 0: Exactly one space required after comma
    return (tagDoc.tag['tag_name'],tagDoc.tag['public_tag_name'],
                                  ^ (bad-whitespace)
C:173, 0: Trailing whitespace (trailing-whitespace)
C:192, 0: Trailing whitespace (trailing-whitespace)
C:193, 0: Trailing whitespace (trailing-whitespace)
C:203, 0: Trailing whitespace (trailing-whitespace)
C:206, 0: Trailing whitespace (trailing-whitespace)
C:208, 0: Exactly one space required after comma
                    tagInfo = {"tag_name":tagName,"public_tag_name":tag[0],
                                                 ^ (bad-whitespace)
C:209, 0: Exactly one space required after comma
                               "tag_class":tagClass,"sample_date":sampleDate,
                                                   ^ (bad-whitespace)
C:210, 0: Trailing whitespace (trailing-whitespace)
C:214, 0: Trailing whitespace (trailing-whitespace)
C:216, 0: Trailing whitespace (trailing-whitespace)
C:218, 0: Exactly one space required after comma
                    tagInfo = {"tag_name":tagName,"public_tag_name":tag[0],
                                                 ^ (bad-whitespace)
C:219, 0: Exactly one space required after comma
                               "tag_class":tagClass,"sample_date":sampleDate,
                                                   ^ (bad-whitespace)
C:220, 0: Trailing whitespace (trailing-whitespace)
C:227, 0: Trailing whitespace (trailing-whitespace)
C:228, 0: Trailing whitespace (trailing-whitespace)
C:229, 0: Trailing whitespace (trailing-whitespace)
C:230, 0: Line too long (118/100) (line-too-long)
C:231, 0: Trailing whitespace (trailing-whitespace)
C:234, 0: Trailing whitespace (trailing-whitespace)
C:239, 0: Wrong continued indentation (add 5 spaces).
                                        f"{tagName} @ date " +
                                        ^    | (bad-continuation)
C:240, 0: Wrong continued indentation (add 5 spaces).
                                        f"{sampleDate}: "+
                                        ^    | (bad-continuation)
C:241, 0: Wrong continued indentation (add 5 spaces).
                                        f"{confLevel} based on" +
                                        ^    | (bad-continuation)
C:242, 0: Wrong continued indentation (add 5 spaces).
                                        f" age of {dateDiff.days} days")
                                        ^    | (bad-continuation)
C:247, 0: Wrong continued indentation (add 1 space).
                                            f"{tagName} @ date " +
                                            ^| (bad-continuation)
C:248, 0: Wrong continued indentation (add 1 space).
                                            f"{sampleDate}: "+
                                            ^| (bad-continuation)
C:249, 0: Wrong continued indentation (add 1 space).
                                            f"{confLevel} based on" +
                                            ^| (bad-continuation)
C:250, 0: Wrong continued indentation (add 1 space).
                                            f" age of {dateDiff.days} days")
                                            ^| (bad-continuation)
C:252, 0: Exactly one space required after comma
                    tagInfo = {"tag_name":tagName,"public_tag_name":tag[0],
                                                 ^ (bad-whitespace)
C:253, 0: Wrong continued indentation (remove 1 space).
                                "tag_class":tagClass,"sample_date":sampleDate,
                               |^ (bad-continuation)
C:253, 0: Exactly one space required after comma
                                "tag_class":tagClass,"sample_date":sampleDate,
                                                    ^ (bad-whitespace)
C:254, 0: Wrong continued indentation (remove 1 space).
                                "file_type":sampleFileType, 
                               |^ (bad-continuation)
C:254, 0: Trailing whitespace (trailing-whitespace)
C:255, 0: Wrong continued indentation (remove 1 space).
                                "confidence_level":confLevel}
                               |^ (bad-continuation)
C:258, 0: Trailing whitespace (trailing-whitespace)
C:259, 0: Trailing whitespace (trailing-whitespace)
C:260, 0: Trailing whitespace (trailing-whitespace)
C:262, 0: Wrong continued indentation (remove 1 space).
                            "public_tag_name":"Not Available",
                           |^ (bad-continuation)
C:263, 0: Wrong continued indentation (remove 1 space).
                            "tag_class":"Not Available",
                           |^ (bad-continuation)
C:264, 0: Wrong continued indentation (remove 1 space).
                            "sample_date":"2000-01-01T00:00:00",
                           |^ (bad-continuation)
C:265, 0: Wrong continued indentation (remove 1 space).
                            "file_type":"Not Available", 
                           |^ (bad-continuation)
C:265, 0: Trailing whitespace (trailing-whitespace)
C:266, 0: Wrong continued indentation (remove 1 space).
                            "confidence_level":0}
                           |^ (bad-continuation)
C:268, 0: Trailing whitespace (trailing-whitespace)
C:271, 0: Trailing whitespace (trailing-whitespace)
C:277, 0: Trailing whitespace (trailing-whitespace)
C:278, 0: Trailing whitespace (trailing-whitespace)
C:279, 0: Trailing whitespace (trailing-whitespace)
C:282, 0: Exactly one space required before assignment
    apiKey= app.config['AUTOFOCUS_API_KEY']
          ^ (bad-whitespace)
C:289, 0: Trailing whitespace (trailing-whitespace)
C:290, 0: Wrong continued indentation (remove 2 spaces).
                    "query": {
                  | ^ (bad-continuation)
C:291, 0: Trailing whitespace (trailing-whitespace)
C:295, 0: Trailing whitespace (trailing-whitespace)
C:296, 0: Wrong continued indentation (remove 2 spaces).
                    "size": 10, 
                  | ^ (bad-continuation)
C:296, 0: Trailing whitespace (trailing-whitespace)
C:297, 0: Wrong continued indentation (remove 2 spaces).
                    "from": 0,
                  | ^ (bad-continuation)
C:298, 0: Wrong continued indentation (remove 2 spaces).
                    "sort": {"create_date": {"order": "desc"}}, 
                  | ^ (bad-continuation)
C:298, 0: Trailing whitespace (trailing-whitespace)
C:299, 0: Wrong continued indentation (remove 2 spaces).
                    "scope": "global", 
                  | ^ (bad-continuation)
C:299, 0: Trailing whitespace (trailing-whitespace)
C:300, 0: Wrong continued indentation (remove 2 spaces).
                    "artifactSource": "af"}
                  | ^ (bad-continuation)
C:301, 0: Trailing whitespace (trailing-whitespace)
C:302, 0: Trailing whitespace (trailing-whitespace)
C:305, 0: Exactly one space required after comma
    queryResponse = requests.post(url=searchURL,headers=headers,
                                               ^ (bad-whitespace)
C:309, 0: Trailing whitespace (trailing-whitespace)
C:313, 0: Trailing whitespace (trailing-whitespace)
C:317, 0: Trailing whitespace (trailing-whitespace)
C:318, 0: Trailing whitespace (trailing-whitespace)
C:321, 0: Exactly one space required after comma
            cookieResults = requests.post(url=cookieURL,headers=headers,
                                                       ^ (bad-whitespace)
C:322, 0: Wrong continued indentation (add 2 spaces).
                                        data=json.dumps(resultData))
                                        ^ | (bad-continuation)
C:324, 0: No space allowed before :
            if domainData['af_complete_percentage'] >= maxPercentage :
                                                                     ^ (bad-whitespace)
C:338, 0: Trailing whitespace (trailing-whitespace)
C:341, 0: Exactly one space required after comparison
    if domainData['total'] !=0:
                           ^^ (bad-whitespace)
C:345, 0: Wrong continued indentation (add 1 space).
                             hits['_source']['filetype'],
                             ^| (bad-continuation)
C:346, 0: Wrong continued indentation (add 1 space).
                             tagList))
                             ^| (bad-continuation)
C:347, 0: Trailing whitespace (trailing-whitespace)
C:350, 0: Exactly one space required after comma
        domainObj.append(('2000-01-01T00:00:00','None',[('Not Available for Domain',
                                               ^ (bad-whitespace)
C:350, 0: Exactly one space required after comma
        domainObj.append(('2000-01-01T00:00:00','None',[('Not Available for Domain',
                                                      ^ (bad-whitespace)
C:351, 0: Wrong continued indentation (add 32 spaces).
                         'Not Available for Domain', 'Not Available for Domain')]))
                         ^                               | (bad-continuation)
C:352, 0: Trailing whitespace (trailing-whitespace)
C:361, 0: Trailing whitespace (trailing-whitespace)
C:367, 0: Trailing whitespace (trailing-whitespace)
C:368, 0: Wrong continued indentation (remove 3 spaces).
                    datetime.timedelta(days=app.config['DNS_DOMAIN_INFO_MAX_AGE']))
                 |  ^ (bad-continuation)
C:375, 0: Trailing whitespace (trailing-whitespace)
C:399, 0: Exactly one space required after comma
            domainDoc = DomainDetailsDoc(meta={'id': domainName},name=domainName)
                                                                ^ (bad-whitespace)
C:405, 0: Trailing whitespace (trailing-whitespace)
C:410, 0: Final newline missing (missing-final-newline)
C:  1, 0: Missing module docstring (missing-docstring)
E:  6, 0: Unable to import 'project' (import-error)
E:  8, 0: Unable to import 'elasticsearch.exceptions' (import-error)
E:  9, 0: Unable to import 'project.dns.dns' (import-error)
E: 10, 0: Unable to import 'elasticsearch_dsl' (import-error)
C: 14, 0: Function name "updateAfStats" doesn't conform to snake_case naming style (invalid-name)
C: 14, 0: Argument name "afInfo" doesn't conform to snake_case naming style (invalid-name)
C: 24, 8: Variable name "afDoc" doesn't conform to snake_case naming style (invalid-name)
C: 29, 8: Variable name "afDoc" doesn't conform to snake_case naming style (invalid-name)
W: 26, 4: Unused variable 'nfe' (unused-variable)
C: 49, 0: Function name "getTagInfo" doesn't conform to snake_case naming style (invalid-name)
C: 49, 0: Argument name "tagName" doesn't conform to snake_case naming style (invalid-name)
C: 58, 4: Variable name "searchURL" doesn't conform to snake_case naming style (invalid-name)
C: 65, 4: Variable name "queryResponse" doesn't conform to snake_case naming style (invalid-name)
C: 67, 4: Variable name "queryData" doesn't conform to snake_case naming style (invalid-name)
C: 75, 0: Function name "processTagList" doesn't conform to snake_case naming style (invalid-name)
C: 75, 0: Argument name "tagObj" doesn't conform to snake_case naming style (invalid-name)
C: 75, 0: Missing function docstring (missing-docstring)
C: 76, 4: Variable name "tagList" doesn't conform to snake_case naming style (invalid-name)
C: 84,12: Variable name "tagName" doesn't conform to snake_case naming style (invalid-name)
C: 87,12: Variable name "tagData" doesn't conform to snake_case naming style (invalid-name)
C: 92, 8: Variable name "tagData" doesn't conform to snake_case naming style (invalid-name)
C:100, 0: Function name "processTag" doesn't conform to snake_case naming style (invalid-name)
C:100, 0: Argument name "tagName" doesn't conform to snake_case naming style (invalid-name)
C:106, 4: Variable name "tagDoc" doesn't conform to snake_case naming style (invalid-name)
C:107, 4: Variable name "updateDetails" doesn't conform to snake_case naming style (invalid-name)
C:108, 4: Variable name "afApiKey" doesn't conform to snake_case naming style (invalid-name)
C:110, 4: Variable name "retStatusFail" doesn't conform to snake_case naming style (invalid-name)
C:112, 4: Variable name "timeLimit" doesn't conform to snake_case naming style (invalid-name)
C:119, 8: Variable name "tagDoc" doesn't conform to snake_case naming style (invalid-name)
C:126,12: Variable name "updateDetails" doesn't conform to snake_case naming style (invalid-name)
C:127,12: Variable name "updateType" doesn't conform to snake_case naming style (invalid-name)
C:136, 8: Variable name "updateDetails" doesn't conform to snake_case naming style (invalid-name)
C:137, 8: Variable name "updateType" doesn't conform to snake_case naming style (invalid-name)
C:142, 8: Variable name "afTagData" doesn't conform to snake_case naming style (invalid-name)
C:149,12: Variable name "tagDoc" doesn't conform to snake_case naming style (invalid-name)
C:163,12: Variable name "tagDoc" doesn't conform to snake_case naming style (invalid-name)
W:108, 4: Unused variable 'afApiKey' (unused-variable)
W:110, 4: Unused variable 'retStatusFail' (unused-variable)
W:134, 4: Unused variable 'nfe' (unused-variable)
C:176, 0: Function name "assessTags" doesn't conform to snake_case naming style (invalid-name)
C:176, 0: Argument name "tagsObj" doesn't conform to snake_case naming style (invalid-name)
C:182, 4: Variable name "confLevel" doesn't conform to snake_case naming style (invalid-name)
C:183, 4: Variable name "taggedEvent" doesn't conform to snake_case naming style (invalid-name)
C:184, 4: Variable name "tagConfLevels" doesn't conform to snake_case naming style (invalid-name)
C:198,12: Variable name "sampleDate" doesn't conform to snake_case naming style (invalid-name)
C:199,12: Variable name "sampleFileType" doesn't conform to snake_case naming style (invalid-name)
C:201,16: Variable name "tagName" doesn't conform to snake_case naming style (invalid-name)
C:202,16: Variable name "tagClass" doesn't conform to snake_case naming style (invalid-name)
C:208,20: Variable name "tagInfo" doesn't conform to snake_case naming style (invalid-name)
C:212,20: Variable name "taggedEvent" doesn't conform to snake_case naming style (invalid-name)
C:218,20: Variable name "tagInfo" doesn't conform to snake_case naming style (invalid-name)
C:222,20: Variable name "taggedEvent" doesn't conform to snake_case naming style (invalid-name)
C:230,20: Variable name "dateDiff" doesn't conform to snake_case naming style (invalid-name)
C:237,28: Variable name "confLevel" doesn't conform to snake_case naming style (invalid-name)
C:245,28: Variable name "confLevel" doesn't conform to snake_case naming style (invalid-name)
C:252,20: Variable name "tagInfo" doesn't conform to snake_case naming style (invalid-name)
C:256,20: Variable name "taggedEvent" doesn't conform to snake_case naming style (invalid-name)
R:196, 4: Too many nested blocks (6/5) (too-many-nested-blocks)
C:261,16: Variable name "tagInfo" doesn't conform to snake_case naming style (invalid-name)
C:267,16: Variable name "taggedEvent" doesn't conform to snake_case naming style (invalid-name)
C:275, 0: Function name "getDomainInfo" doesn't conform to snake_case naming style (invalid-name)
C:275, 0: Argument name "threatDomain" doesn't conform to snake_case naming style (invalid-name)
R:275, 0: Too many local variables (19/15) (too-many-locals)
C:282, 4: Variable name "apiKey" doesn't conform to snake_case naming style (invalid-name)
C:283, 4: Variable name "searchURL" doesn't conform to snake_case naming style (invalid-name)
C:284, 4: Variable name "resultURL" doesn't conform to snake_case naming style (invalid-name)
C:285, 4: Variable name "lookupTimeout" doesn't conform to snake_case naming style (invalid-name)
C:286, 4: Variable name "maxPercentage" doesn't conform to snake_case naming style (invalid-name)
C:287, 4: Variable name "resultData" doesn't conform to snake_case naming style (invalid-name)
C:289, 4: Variable name "searchData" doesn't conform to snake_case naming style (invalid-name)
C:305, 4: Variable name "queryResponse" doesn't conform to snake_case naming style (invalid-name)
C:308, 4: Variable name "queryData" doesn't conform to snake_case naming style (invalid-name)
C:312, 8: Variable name "cookieURL" doesn't conform to snake_case naming style (invalid-name)
C:321,12: Variable name "cookieResults" doesn't conform to snake_case naming style (invalid-name)
C:323,12: Variable name "domainData" doesn't conform to snake_case naming style (invalid-name)
C:339, 4: Variable name "domainObj" doesn't conform to snake_case naming style (invalid-name)
C:343,12: Variable name "tagList" doesn't conform to snake_case naming style (invalid-name)
C:359, 0: Function name "getDomainDoc" doesn't conform to snake_case naming style (invalid-name)
C:359, 0: Argument name "domainName" doesn't conform to snake_case naming style (invalid-name)
C:364, 4: Variable name "domainDoc" doesn't conform to snake_case naming style (invalid-name)
C:365, 4: Variable name "updateDetails" doesn't conform to snake_case naming style (invalid-name)
C:367, 4: Variable name "timeLimit" doesn't conform to snake_case naming style (invalid-name)
C:374, 8: Variable name "domainDoc" doesn't conform to snake_case naming style (invalid-name)
C:381,12: Variable name "updateDetails" doesn't conform to snake_case naming style (invalid-name)
C:382,12: Variable name "updateType" doesn't conform to snake_case naming style (invalid-name)
C:390, 8: Variable name "updateDetails" doesn't conform to snake_case naming style (invalid-name)
C:391, 8: Variable name "updateType" doesn't conform to snake_case naming style (invalid-name)
W:404,15: Catching too general exception Exception (broad-except)
C:398,12: Variable name "afDomainData" doesn't conform to snake_case naming style (invalid-name)
C:399,12: Variable name "domainDoc" doesn't conform to snake_case naming style (invalid-name)
C:404, 8: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
C:406,12: Variable name "domainDoc" doesn't conform to snake_case naming style (invalid-name)
W:382,12: Unused variable 'updateType' (unused-variable)
W:388, 4: Unused variable 'nfe' (unused-variable)
W: 10, 0: Unused DocType imported from elasticsearch_dsl (unused-import)
W: 10, 0: Unused Search imported from elasticsearch_dsl (unused-import)
W: 10, 0: Unused Date imported from elasticsearch_dsl (unused-import)
W: 10, 0: Unused Integer imported from elasticsearch_dsl (unused-import)
W: 10, 0: Unused Keyword imported from elasticsearch_dsl (unused-import)
W: 10, 0: Unused Text imported from elasticsearch_dsl (unused-import)
W: 10, 0: Unused Ip imported from elasticsearch_dsl (unused-import)
W: 10, 0: Unused connections imported from elasticsearch_dsl (unused-import)
C:  5, 0: standard import "import datetime" should be placed before "import requests" (wrong-import-order)
C:  7, 0: standard import "from ast import literal_eval" should be placed before "import requests" (wrong-import-order)
C:  9, 0: Imports from package project are not grouped (ungrouped-imports)

------------------------------------
Your code has been rated at -3.35/10

**Comment by sdndude** [comment]
This is fixed in 79f1dab21906b363f73aa182eb155d871b614f94
