### ISSUE TITLE
runner.py score -3.21/10 pylint

### ISSUE THREAD

**Issue by cmj77** [PaloAltoNetworks/safe-networking-sp#49]
************* Module runner
C: 18, 0: Trailing whitespace (trailing-whitespace)
C: 19, 0: Trailing whitespace (trailing-whitespace)
C: 20, 0: Trailing whitespace (trailing-whitespace)
C: 31, 0: Trailing whitespace (trailing-whitespace)
C: 47, 0: Exactly one space required after assignment
    searchResponse =  eventSearch.execute()
                   ^ (bad-whitespace)
C: 48, 0: Trailing whitespace (trailing-whitespace)
C: 55, 0: Trailing whitespace (trailing-whitespace)
C: 69, 0: Trailing whitespace (trailing-whitespace)
C: 70, 0: Trailing whitespace (trailing-whitespace)
C: 79, 0: Trailing whitespace (trailing-whitespace)
C: 80, 0: Trailing whitespace (trailing-whitespace)
C: 82, 0: Trailing whitespace (trailing-whitespace)
C: 87, 0: Trailing whitespace (trailing-whitespace)
C: 89, 0: Trailing whitespace (trailing-whitespace)
C: 93, 0: Trailing whitespace (trailing-whitespace)
C: 96, 0: Trailing whitespace (trailing-whitespace)
C:113, 0: Trailing whitespace (trailing-whitespace)
C:115, 0: Trailing whitespace (trailing-whitespace)
C:117, 0: Trailing whitespace (trailing-whitespace)
C:140, 0: Trailing whitespace (trailing-whitespace)
C:147, 0: Trailing whitespace (trailing-whitespace)
C:150, 0: Trailing whitespace (trailing-whitespace)
C:157, 0: Wrong continued indentation (add 1 space).
                                f" {eventDoc}")
                                ^| (bad-continuation)
C:158, 0: Unnecessary parens after 'return' keyword (superfluous-parens)
C:161, 0: Wrong continued indentation (add 1 space).
                                f" {te.info} ")
                                ^| (bad-continuation)
C:162, 0: Unnecessary parens after 'return' keyword (superfluous-parens)
C:165, 0: Unnecessary parens after 'return' keyword (superfluous-parens)
C:166, 0: Trailing whitespace (trailing-whitespace)
W:168, 0: Bad indentation. Found 16 spaces, expected 8 (bad-indentation)
W:169, 0: Bad indentation. Found 16 spaces, expected 8 (bad-indentation)
C:169, 0: Unnecessary parens after 'return' keyword (superfluous-parens)
C:170, 0: Trailing whitespace (trailing-whitespace)
C:179, 0: Final newline missing (missing-final-newline)
C:  1, 0: Missing module docstring (missing-docstring)
E:  3, 0: Unable to import 'project' (import-error)
E:  4, 0: Unable to import 'elasticsearch_dsl' (import-error)
E:  7, 0: Unable to import 'project.dns.dns' (import-error)
E:  8, 0: Unable to import 'elasticsearch' (import-error)
E:  9, 0: Unable to import 'elasticsearch_dsl' (import-error)
E: 10, 0: Unable to import 'elasticsearch.exceptions' (import-error)
E: 11, 0: Unable to import 'project.dns.dnsutils' (import-error)
C: 16, 0: Function name "processDNS" doesn't conform to snake_case naming style (invalid-name)
C: 26, 4: Variable name "priDocIds" doesn't conform to snake_case naming style (invalid-name)
C: 27, 4: Variable name "secDocIds" doesn't conform to snake_case naming style (invalid-name)
C: 28, 4: Variable name "qSize" doesn't conform to snake_case naming style (invalid-name)
C: 29, 4: Variable name "timeLimit" doesn't conform to snake_case naming style (invalid-name)
C: 30, 4: Variable name "updateDetails" doesn't conform to snake_case naming style (invalid-name)
C: 38, 4: Variable name "eventSearch" doesn't conform to snake_case naming style (invalid-name)
C: 44, 4: Variable name "eventSearch" doesn't conform to snake_case naming style (invalid-name)
C: 47, 4: Variable name "searchResponse" doesn't conform to snake_case naming style (invalid-name)
C: 58, 8: Variable name "domainSearch" doesn't conform to snake_case naming style (invalid-name)
W: 83,-1: String statement has no effect (pointless-string-statement)
W:103,19: Catching too general exception Exception (broad-except)
C:103,12: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
W:109,19: Catching too general exception Exception (broad-except)
C:109,12: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
W: 29, 4: Unused variable 'timeLimit' (unused-variable)
W: 30, 4: Unused variable 'updateDetails' (unused-variable)
C:115, 0: Function name "searchDomain" doesn't conform to snake_case naming style (invalid-name)
C:115, 0: Argument name "eventID" doesn't conform to snake_case naming style (invalid-name)
C:124, 4: Variable name "processedValue" doesn't conform to snake_case naming style (invalid-name)
W:167,11: Catching too general exception Exception (broad-except)
C:127, 8: Variable name "eventDoc" doesn't conform to snake_case naming style (invalid-name)
C:128, 8: Variable name "domainName" doesn't conform to snake_case naming style (invalid-name)
C:129, 8: Variable name "domainDoc" doesn't conform to snake_case naming style (invalid-name)
C:140,16: Variable name "eventTag" doesn't conform to snake_case naming style (invalid-name)
C:146,16: Variable name "processedValue" doesn't conform to snake_case naming style (invalid-name)
C:148,16: Variable name "eventTag" doesn't conform to snake_case naming style (invalid-name)
C:149,16: Variable name "processedValue" doesn't conform to snake_case naming style (invalid-name)
W:163,19: Catching too general exception Exception (broad-except)
C:159,12: Variable name "te" doesn't conform to snake_case naming style (invalid-name)
C:163,12: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
C:167, 4: Variable name "e" doesn't conform to snake_case naming style (invalid-name)
R:115, 0: Either all return statements in a function should return an expression, or none of them should. (inconsistent-return-statements)
C:173, 0: Missing function docstring (missing-docstring)
W:  1, 0: Unused import time (unused-import)
W: 10, 0: Unused NotFoundError imported from elasticsearch.exceptions (unused-import)
C:  5, 0: standard import "from multiprocessing import cpu_count" should be placed before "from project import app" (wrong-import-order)
C:  6, 0: standard import "from multiprocessing.dummy import Pool" should be placed before "from project import app" (wrong-import-order)
C:  7, 0: Imports from package project are not grouped (ungrouped-imports)
C:  9, 0: Imports from package elasticsearch_dsl are not grouped (ungrouped-imports)
C: 10, 0: Imports from package elasticsearch are not grouped (ungrouped-imports)
C: 11, 0: Imports from package project are not grouped (ungrouped-imports)

------------------------------------
Your code has been rated at -3.21/10

**Comment by sdndude** [comment]
Thanks for these. If you can tell me the tools you used, I will add them to the automated testing.

**Comment by sdndude** [comment]
This is fixed in 79f1dab21906b363f73aa182eb155d871b614f94
