### ISSUE TITLE
public = empty directory

### ISSUE THREAD

**Issue by cmj77** [PaloAltoNetworks/safe-networking-sp#51]
Is it needed?

**Comment by sdndude** [comment]
Where is this?  Full paths from the root of safe-networking are needed as this is a large repo.  
The only public that I see is under project/client and it has 2 directories and a file under it.  Is there another public directory somewhere?

**Comment by sdndude** [comment]
There is only one public directory in the entire repo and that is ./project/client/public
It is not empty:
earcuri@DFWMACW116G8WL-$ pwd
/Users/earcuri/myDev/safe-networking-sp/project/client/public

[~/myDev/safe-networking-sp/project/client/public]
earcuri@DFWMACW116G8WL-$ ls -al
total 8
drwxr-xr-x   5 earcuri  PALOALTONETWORK\Domain Users  170 Jan 30 17:10 .
drwxr-xr-x  10 earcuri  PALOALTONETWORK\Domain Users  340 Jan 30 17:10 ..
drwxr-xr-x   7 earcuri  PALOALTONETWORK\Domain Users  238 Jan 30 17:10 images
-rw-r--r--   1 earcuri  PALOALTONETWORK\Domain Users  471 Jan 30 17:10 index.html
drwxr-xr-x   3 earcuri  PALOALTONETWORK\Domain Users  102 Jan 30 17:10 styles

Closing
