### ISSUE TITLE
sfn score -1.32/10

### ISSUE THREAD

**Issue by cmj77** [PaloAltoNetworks/safe-networking-sp#58]
************* Module sfn
C:  4, 0: Trailing whitespace (trailing-whitespace)
C:  6, 0: Trailing whitespace (trailing-whitespace)
C:  7, 0: Trailing whitespace (trailing-whitespace)
C: 17, 0: Trailing whitespace (trailing-whitespace)
C: 18, 0: Trailing whitespace (trailing-whitespace)
C: 19, 0: Trailing whitespace (trailing-whitespace)
C: 22, 0: Trailing whitespace (trailing-whitespace)
C: 24, 0: Trailing whitespace (trailing-whitespace)
C: 26, 0: Trailing whitespace (trailing-whitespace)
C: 33, 0: Trailing whitespace (trailing-whitespace)
C: 35, 0: Trailing whitespace (trailing-whitespace)
C: 45, 0: Trailing whitespace (trailing-whitespace)
C: 51, 0: Trailing whitespace (trailing-whitespace)
C: 52, 0: Trailing whitespace (trailing-whitespace)
C: 54, 0: Trailing whitespace (trailing-whitespace)
C: 61, 0: Trailing whitespace (trailing-whitespace)
C: 65, 0: Trailing whitespace (trailing-whitespace)
W: 73, 0: Bad indentation. Found 20 spaces, expected 16 (bad-indentation)
C: 74, 0: Trailing whitespace (trailing-whitespace)
W: 74, 0: Bad indentation. Found 20 spaces, expected 16 (bad-indentation)
C: 75, 0: Trailing whitespace (trailing-whitespace)
C: 21, 0: Missing function docstring (missing-docstring)
C: 23, 4: Function name "runDNS" doesn't conform to snake_case naming style (invalid-name)
C: 34, 4: Function name "runIoT" doesn't conform to snake_case naming style (invalid-name)
C: 43, 4: Variable name "threadDNS" doesn't conform to snake_case naming style (invalid-name)
C: 46, 4: Variable name "threadIoT" doesn't conform to snake_case naming style (invalid-name)
C: 50, 0: Function name "initBackgroundProcs" doesn't conform to snake_case naming style (invalid-name)
C: 62, 4: Function name "initProcs" doesn't conform to snake_case naming style (invalid-name)
C: 62, 4: Missing function docstring (missing-docstring)
W: 72,12: No exception type(s) specified (bare-except)
C: 68,16: Variable name "r" doesn't conform to snake_case naming style (invalid-name)
W: 80, 0: Wildcard import project.views (wildcard-import)
C: 80, 0: Import "from project.views import *" should be placed at the top of the module (wrong-import-position)
W: 13, 0: Unused es imported from project (unused-import)
W: 80, 0: Unused import sfn_blueprint from wildcard import (unused-wildcard-import)
W: 80, 0: Unused import index from wildcard import (unused-wildcard-import)
W: 80, 0: Unused import Blueprint from wildcard import (unused-wildcard-import)
W: 80, 0: Unused import jsonify from wildcard import (unused-wildcard-import)
W: 80, 0: Unused import request from wildcard import (unused-wildcard-import)
W: 80, 0: Unused import render_template from wildcard import (unused-wildcard-import)
W: 80, 0: Unused import current_app from wildcard import (unused-wildcard-import)
W: 80, 0: Unused import flash from wildcard import (unused-wildcard-import)
C: 12, 0: standard import "import threading" should be placed before "import requests" (wrong-import-order)

------------------------------------
Your code has been rated at -1.32/10

**Comment by sdndude** [comment]
What tool(s) did you use for this?  A lot of this should be fixed in the develop branch already.

**Comment by sdndude** [comment]
This is fixed in 79f1dab21906b363f73aa182eb155d871b614f94
