### ISSUE TITLE
setup.sh

### ISSUE THREAD

**Issue by cmj77** [PaloAltoNetworks/safe-networking-sp#59]
Do you want to convert this to python?

**Comment by sdndude** [comment]
Maybe.  There is still a lot of work that needs to be done to it to get it where it needs to be.  We can look at it once we decide what all needs to be done with it from a workflow perspective.  This is *not* however your typical setup.py where it gets installed as a module.  It is for easing the installation burden.

**Comment by sdndude** [comment]
This won't be converted to python and we are pushing this off until 3.0 where we will try to fully automate the installation and configuration of SafeNetworking and all of it's supporting software.
